name: Update Comment on Issue Close
on:
  issues:
    types: [closed]
jobs:
  find-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Find existing workflow comment
        id: find_comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- COMMON_COMMENT -->'

      - name: Fetch existing comment body
        if: steps.find_comment.outputs.comment-id != ''
        run: |
          gh api repos/${{ github.repository }}/issues/comments/${{ steps.find_comment.outputs.comment-id }} > comment.json

      - name: Replace STAT_PART in body
        if: steps.find_comment.outputs.comment-id != ''
        run: |
          jq -r .body comment.json > old_body.md
          awk 'BEGIN {in=0} /<!-- STAT_PART -->/ {print; print "⚠️ 此 Issue 已被关闭  \n\n任何新的评论可能不会被注意到, 如还未解决, 或您有新问题, 请创建另一个 Issue  "; in=1; next} /<!-- STAT_PART_END -->/ {in=0} !in' old_body.md > new_body.md

      - name: Update workflow comment
        if: steps.find_comment.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          body-path: new_body.md
          edit-mode: replace
