name: Update Comment on Issue Close
on:
  issues:
    types: [closed]
permissions:
  issues: write
jobs:
  update-stat:
    runs-on: ubuntu-latest
    steps:
      - name: Find existing workflow comment
        id: find_comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- COMMON_COMMENT -->'
      - name: Update STAT_PART via GitHub Script
        if: steps.find_comment.outputs.comment-id != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commentId = parseInt(process.env.COMMENT_ID, 10);
            // 获取现有评论
            const { data: comment } = await github.rest.issues.getComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: commentId
            });
            const oldBody = comment.body;
            // 替换 STAT_PART
            const newBody = oldBody.replace(
              /<!-- STAT_PART -->[\s\S]*?<!-- STAT_PART_END -->/,
              '<!-- STAT_PART -->\n⚠️ 此 Issue 已被关闭\n\n任何新的评论可能不会被注意到, 如还未解决, 或您有新问题, 请创建另一个 Issue\n<!-- STAT_PART_END -->'
            );
            // 更新评论
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: commentId,
              body: newBody
            });
        env:
          COMMENT_ID: ${{ steps.find_comment.outputs.comment-id }}
